name: Run Azure Login with User-assigned Managed Identity
on:
  push:
    branches:
      - main

jobs: 
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          enable-AzPSSession: true

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure PowerShell script
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext
