name: Restart Azure Spring App

on:
  push:

jobs:
  restart_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      run: |
        az login --service-principal -u "<clientId>" -p "<clientSecret>" --tenant "<tenantId>"

    - name: Restart Azure Spring App
      run: |
        az spring-cloud app restart --name your-app-name --resource-group your-resource-group
