name: Azure Spring App Management

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Manage Spring App (start, stop, restart)'
        required: true
        options:
          - start
          - stop
          - restart
      app_name:
        type: choice
        description: 'Name of the Azure Spring App'
        required: true
        options:
          - ALL            # Add 'ALL' as an option
          - hello-world-app
          - another-app-name
          - yet-another-app-name

jobs:
  manage-spring-app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get list of app names
        id: get-app-names
        run: |
          if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
            app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
          else
            app_names="${{ github.event.inputs.app_name }}"
          fi
          echo "::set-output name=app_names::$app_names"

      - name: Execute action on app
        run: |
          for app_name in ${{ steps.get-app-names.outputs.app_names }}; do
            if [ "${{ github.event.inputs.action }}" == "start" ]; then
              az spring app start --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
              az spring app stop --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            elif [ "${{ github.event.inputs.action }}" == "restart" ]; then
              az spring app restart --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            fi
          done
        env:
          AZURE_APP_NAME: ${{ steps.get-app-names.outputs.app_names }}
