name: Azure Spring App Management

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Manage Spring App (start, stop, restart)'
        required: true
        options:
          - start
          - stop
          - restart

jobs:
  manage-spring-app:
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          clientSecret:  ""
          subscriptionId:  ""
          tenantId:  ""
          clientId:  ""

      - name: Manage Azure Spring App
        run: |
          if [ "${{ github.event.inputs.action }}" == "start" ]; then
            az spring app start --name "hello-world-app" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
            az spring app stop --name "hello-world-app" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "restart" ]; then
            az spring app restart --name "hello-world-app" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          fi
