name: Azure Spring App Management

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Manage Spring App (start, stop, restart)'
        required: true
        options:
          - start
          - stop
          - restart
      app_name:
        type: string
        description: 'Name of the Azure Spring App (Use "ALL" to apply action to all apps)'
        required: true

jobs:
  manage-spring-app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Execute action on app
        run: |
          if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
            app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
          else
            app_names="${{ github.event.inputs.app_name }}"
          fi

          for app_name in $app_names; do
            if [ "${{ github.event.inputs.action }}" == "start" ]; then
              az spring app start --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
              az spring app stop --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            elif [ "${{ github.event.inputs.action }}" == "restart" ]; then
              az spring app restart --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            fi
          done
        shell: bash

      - name: Check for errors
        run: |
          if [ $? -ne 0 ]; then
            echo "An error occurred while executing the action on the app."
            exit 1
          fi
        shell: bash

  validate-app-status:
    runs-on: self-hosted
    needs: manage-spring-app
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Wait for apps to start/stop/restart
        run: sleep 300  # Wait for 5 minutes
        shell: bash
  
      - name: Validate app status
        run: |
          if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
            app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
          else
            app_names="${{ github.event.inputs.app_name }}"
          fi
  
          for app_name in $app_names; do
            status=$(az spring app show --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "properties.activeDeployment.properties.status" -o tsv)
            if [ $? -eq 0 ]; then
              if [ -z "$status" ]; then
                echo "App $app_name status: Not started/stopped yet."
              else
                echo "App $app
