name: Azure Spring App Management

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Manage Spring App (start, stop, restart)'
        required: true
        options:
          - start
          - stop
          - restart
      app_name:
        type: choice
        description: 'Name of the Azure Spring App'
        required: true
        options:
          - ALL            # Add 'ALL' as an option
          - hello-world-app
          - hello-india
          - yet-another-app-name

jobs:
  manage-spring-app:
    runs-on: self-hosted
    strategy:
      matrix:
        app_name: ${{fromJson(needs.get-app-names.outputs.app_names)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Execute action on app
        run: |
          if [ "${{ matrix.app_name }}" == "ALL" ]; then
            app_names=$(echo "${{ needs.get-app-names.outputs.app_names }}" | tr ',' '\n')
          else
            app_names="${{ matrix.app_name }}"
          fi

          for app_name in $app_names; do
            if [ "${{ github.event.inputs.action }}" == "start" ]; then
              az spring app start --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
              az spring app stop --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            elif [ "${{ github.event.inputs.action }}" == "restart" ]; then
              az spring app restart --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg" &
            fi
          done
        continue-on-error: true
