name: Azure Spring App Management

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Manage Spring App (start, stop, restart)'
        required: true
        options:
          - start
          - stop
          - restart

jobs:
  manage-spring-app:
    runs-on: self-hosted
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          clientSecret:  "D4x8Q~TubrFIbXL7c_hBpZLTNaHUYt.TzoaNeafL"
          subscriptionId:  "d7b03374-1a6c-489e-aeea-7ee84923bf47"
          tenantId:  "19e689b1-e574-48c3-b0c4-955bb7215eef"
          clientId:  "9c358930-8ffc-41c7-95f5-07cbad713e59"

      - name: Manage Azure Spring App
        run: |
          if [ "${{ github.event.inputs.action }}" == "start" ]; then
            az spring app start --name "hello-world-app" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
            az spring app stop --name "hello-world-app" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "restart" ]; then
            az spring app restart --name "hello-world-app" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          fi
