name: Azure Spring App Management

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Manage Spring App (start, stop, restart)'
        required: true
        options:
          - start
          - stop
          - restart
      app_name:
        type: choice
        description: 'Name of the Azure Spring App'
        required: true
        options:
          - ALL            # Add 'ALL' as an option
          - hello-world-app
          - another-app-name
          - yet-another-app-name

jobs:
  manage-spring-app:
    runs-on: self-hosted
    strategy:
      matrix:
        app_name: ${{ matrix.app_names }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get list of app names
        id: get-app-names
        run: |
          if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
            app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o tsv)
          else
            app_names="${{ github.event.inputs.app_name }}"
          fi
          echo "::set-output name=app_names::$app_names"

      - name: Execute action on app
        run: |
          if [ "${{ github.event.inputs.action }}" == "start" ]; then
            az spring app start --name "${{ matrix.app_name }}" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
            az spring app stop --name "${{ matrix.app_name }}" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "restart" ]; then
            az spring app restart --name "${{ matrix.app_name }}" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          fi
        env:
          AZURE_APP_NAME: ${{ matrix.app_name }}
        continue-on-error: true

  set-matrix:
    needs: manage-spring-app
    runs-on: self-hosted
    steps:
      - name: Set matrix
        run: |
          echo "::set-output name=app_names::${{ steps.get-app-names.outputs.app_names | join('\n') }}"
        id: set-matrix-data

      - name: Create execution matrix
        run: |
          echo "${{ steps.set-matrix-data.outputs.app_names }}"
        id: app-names
        shell: bash

      - name: Finalize matrix
        run: |
          echo "::set-output name=app_names::${{ steps.app-names.outputs.stdout }}"
