name: Azure Spring App Management

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Manage Spring App (start, stop, restart)'
        required: true
        options:
          - start
          - stop
          - restart
      app_name:
        type: choice
        description: 'Name of the Azure Spring App'
        required: true
        options:
          - ALL            # Add 'ALL' as an option
          - hello-world-app
          - hello-india
          - yet-another-app-name

jobs:
  manage-spring-app:
    runs-on: self-hosted
    needs: get-app-names  # Ensure the manage-spring-app job depends on get-app-names
    strategy:
      matrix:
        app_name: ${{fromJson(needs.get-app-names.outputs.app_names)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Execute action on app
        run: |
          if [ "${{ matrix.app_name }}" == "ALL" ]; then
            app_name="${{ github.event.inputs.app_name }}"
          else
            app_name="${{ matrix.app_name }}"
          fi

          if [ "${{ github.event.inputs.action }}" == "start" ]; then
            az spring app start --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "stop" ]; then
            az spring app stop --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          elif [ "${{ github.event.inputs.action }}" == "restart" ]; then
            az spring app restart --name "$app_name" --service "free-trial-spring-app" --resource-group "free-trial-rg"
          fi
        env:
          AZURE_APP_NAME: ${{ matrix.app_name }}
        continue-on-error: true

  get-app-names:
    runs-on: self-hosted
    outputs:
      app_names: ${{ steps.set-app-names.outputs.app_names }}
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get list of app names
        id: set-app-names
        run: |
          if [ "${{ github.event.inputs.app_name }}" == "ALL" ]; then
            app_names=$(az spring app list --service "free-trial-spring-app" --resource-group "free-trial-rg" --query "[].name" -o json)
          else
            app_names="[\"${{ github.event.inputs.app_name }}\"]"
          fi
          echo "::set-output name=app_names::$app_names"
